kind: pipeline
name: default

steps:
  - name: Initialize
    image: hugomods/hugo:0.136.4
    commands:
      - git submodule update --init
      - hugo version

  - name: Build Hugo site
    image: hugomods/hugo:0.136.4
    commands:
      - hugo --minify
    # settings:
    #   hugo_version: 0.135
    #   validate: true

  - name: Check Docker Service
    image: docker
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
    commands:
      - sleep 5
      - docker info

  - name: Build nginx container
    image: docker
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_HOST: tcp://docker:2375 # Use the Docker-in-Docker service
      DOCKER_TLS_CERTDIR: ""
      GITEA_USER: m00se
      GITEA_PASS:
        from_secret: gitea_token
    commands:
      - |
        # Create a Dockerfile for NGINX serving the blog
        cat << EOF > public/Dockerfile
        FROM nginx:alpine
        COPY . /usr/share/nginx/html
        EXPOSE 80
        EOF
      # - docker login -u ${GITEA_USER} -p ${GITEA_PASS} git.hyperios.space
      - docker build -t blog:${DRONE_TAG} ./public
      # - drone push git.hyperios.space/m00se/blog:"${DRONE_TAG}"

  - name: Push Pre-Release to Gitea
    image: plugins/gitea-release
    settings:
      api_key: a4bdd424175f583c64d4aad8c7917bf69afe70c8
      base_url: https://git.hyperios.space
      files:
        - public/**
      checksum: sha256
      draft: false
      title: Release Hugo blog
      note: |
        Hugo blog built by Drone and deployed via NGINX
    when:
      event:
        - tag

services:
  - name: docker
    image: docker:dind
    privileged: true # Use DinD in privileged mode
    environment:
      DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker-in-Docker
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]

trigger:
  branch:
    - main
