---
kind: pipeline
type: docker
name: Test Environment

trigger:
  branch:
    - develop
  event:
    include:
      - push

steps:
  - name: Clone Git Submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update --recursive --remote

  - name: Build with hugo
    image: hugomods/hugo:0.136.4
    commands:
      - hugo version
      - hugo -D --minify

  - name: Publish to GitHub Pages
    image: plugins/gh-pages
    settings:
      username: akshaysth
      password:
        from_secret: gh_password
      pages_directory: public
      copy_contents: true

  # - name: Initialize
  #   image: hugomods/hugo:0.136.4
  #   commands:
  #     - git submodule update --init
  #     - hugo version

  # - name: Build Hugo site
  #   image: hugomods/hugo:0.136.4
  #   commands:
  #     - hugo --minify
  # settings:
  #   hugo_version: 0.135
  #   validate: true

  # - name: Check Docker Service
  #   image: docker
  #   environment:
  #     DOCKER_HOST: tcp://docker:2375
  #     DOCKER_TLS_CERTDIR: ""
  #   commands:
  #     # - sleep 5
  #     - docker info

  # - name: Build nginx container
  #   image: docker
  #   settings:
  #     repo: m00se/blog
  #     dockerfile: public/Dockerfile
  #   environment:
  #     DOCKER_BUILDKIT: 1
  #     DOCKER_HOST: tcp://docker:2375 # Use the Docker-in-Docker service
  #     DOCKER_TLS_CERTDIR: ""
  #     GITEA_USER: m00se
  #     GITEA_PASS:
  #       from_secret: gitea_token
  #   commands:
  #     - echo $GITEA_PASS | docker login --username $GITEA_USER --password-stdin git.hyperios.space
  #     - docker build -t m00se/blog:latest ./public/Dockerfile
  #     - docker build -t m00se/blog:${DRONE_BUILD_NUMBER} ./public/Dockerfile
  #   tags:
  #     - latest
  #     - ${DRONE_BUILD_NUMBER}
  #   when:
  #     event:
  #       - push
  #       - pull_request
  # - name: Tag docker image
  #   image: plugins/docker
  #   settings:
  #     repo: m00se/blog
  #     dockerfile: public/Dockerfile
  #     username: m00se
  #     password:
  #       from_secret: gitea_token
  #   tags:
  #     - latest
  #     - ${DRONE_TAG##v}
  #   when:
  #     event:
  #       - tag
#   - name: Push Pre-Release to Gitea
#     image: plugins/gitea-release
#     settings:
#       api_key:
#         from_secret: gitea_token
#       base_url: https://git.hyperios.space
#       files:
#         - public/**
#       checksum: sha256
#       draft: false
#       title: Release Hugo blog
#       note: |
#         Hugo blog built by Drone and deployed via NGINX
#     when:
#       event:
#         tag

# services:
#   - name: docker
#     image: docker:dind
#     privileged: true # Use DinD in privileged mode
#     environment:
#       DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker-in-Docker
#     command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]

# trigger:
#   branch:
#     - main
