kind: pipeline
name: default

steps:
  - name: Initialize
    image: hugomods/hugo:0.136.4
    commands:
      - git submodule update --init
      - hugo version

  - name: Build Hugo site
    image: hugomods/hugo:0.136.4
    commands:
      - hugo --minify
    # settings:
    #   hugo_version: 0.135
    #   validate: true

  - name: Build nginx container
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - ls -al /var/run/docker.sock
      - |
        # Create a Dockerfile for NGINX serving the blog
        cat << EOF > public/Dockerfile
        FROM nginx:alpine
        COPY . /usr/share/nginx/html
        EXPOSE 80
        EOF
      - docker build -t blog:latest ./public
    
  - name: Push Pre-Release to Gitea
    image: plugins/gitea-release
    settings:
      api_key: a4bdd424175f583c64d4aad8c7917bf69afe70c8
      base_url: https://git.hyperios.space
      files: 
        - public/**
      checksum: sha256
      draft: false
      title: Release Hugo blog
      note: |
        Hugo blog built by Drone and deployed via NGINX

trigger:
  branch: 
    - main
