kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main

steps:
  - name: Initialize
    image: hugomods/hugo:latest
    commands:
      - git submodule update --init
      - hugo version

  - name: Build
    image: hugomods/hugo:latest
    commands:
      - hugo

  - name: publish
    image: plugins/gh-pages
    settings:
      username: akshaysth
      password:
        from_secret: gh_password
      pages_directory: public/
