kind: pipeline
name: default

steps:
  - name: Initialize
    image: hugomods/hugo:0.136.4
    commands:
      - git submodule update --init
      - hugo version

  - name: Build
    image: hugomods/hugo:0.136.4
    commands:
      - hugo
    # settings:
    #   hugo_version: 0.135
    #   validate: true

  - name: publish
    image: plugins/gh-pages
    settings:
      username: akshaysth
      password:
        from_secret: gh_password
      pages_directory: public/
  
  - name: netlify
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_token
      site_id: 1f39aa19-50b0-4e61-9fb6-f0818623416c
