kind: pipeline
name: default

steps:
  - name: Initialize
    image: hugomods/hugo:latest
    commands:
      - git submodule update --init
      - hugo version

  - name: Build
    image: plugins/hugo
    commands:
      - git submodule update --remote
      - hugo
    # settings:
    #   hugo_version: 0.135
    #   validate: true

  - name: publish
    image: plugins/gh-pages
    settings:
      username: akshaysth
      password:
        from_secret: gh_password
      pages_directory: public/
